### ISSUE TITLE
Implement Destroy Claims

### ISSUE THREAD

**Issue by DaTebe** [FraunhoferISST/diva#326]
# Destroy Claims

Data is one of the most important assets in the 21th century.
While a lot of work has been done in the field of selecting, using and transforming data for our needs, little to no work has been done when it comes to the deletion of data.

## Idea

We are going to store the Destroy Claim Model in DIVA.
This will allow us to model the end of the data life cycle at the same place where data is inventoried.

## Tasks/Questions

- [ ] we need a Destroy Claim entity
- [ ] need to decide which fields are supported by DIVA
- [ ] do we need a new API endpoint to access Destroy Claims?
