### ISSUE TITLE
Implement Service Management

### ISSUE THREAD

**Issue by DaTebe** [FraunhoferISST/diva#33]
**Is your feature request related to a problem? Please describe.**
In the future, we want to manage which services are available in DIVA, but also in the company. For this, we need to collect metadata about the services. This will allow us to model more complex relationships.  What is now possible on a small scale with assets can then be expanded in a meaningful way. For example, it will then be possible to describe whether data is processed with services.

**Describe the solution you'd like**
The same logic can be applied as already used by the RM and AM. The use of [lerna](https://github.com/lerna/lerna) avoids further duplication of code.

**Tasks**

- [x] create new JSON Schema for services (reuse existing artifacts)
- [x] update [entity](https://github.com/FraunhoferISST/diva/blob/f30690264516423e9cd89b10d6a54060075c1240/core/schemata/json-schema/artifacts/entity.json#L101) JSON schema
- [x] create new service in core (make use of lerna!)
- [x] write README
- [x] Update DIVA Slides @DaTebe
- [x] update [elasticsearch-connector](https://github.com/FraunhoferISST/diva/tree/main/core/services/elasticsearch-connector) to also process new service events (e.g [here](https://github.com/FraunhoferISST/diva/blob/f30690264516423e9cd89b10d6a54060075c1240/core/services/elasticsearch-connector/index.js#L8)
- [x] update [docker-compose.yml](https://github.com/FraunhoferISST/diva/blob/main/docker/docker-compose.yml)
- [x] update [.env.default](https://github.com/FraunhoferISST/diva/blob/main/docker/.env.default) file
- [x] remeber to create new topic for service events [docker-compose kafka](https://github.com/FraunhoferISST/diva/blob/f30690264516423e9cd89b10d6a54060075c1240/docker/docker-compose.yml#L320)

**Comment by DaTebe** [comment]
@setaman @anatoliynovo let's call together to finish this issue. From my point of view we just need to do 1 or 2 things to approve the PR.

**Comment by setaman** [comment]
@DaTebe yeah, it's close to be approved. Just a few things on JSON schemata need to be discussed. Another point is that we have no UI for this feature, neither creation form nor details view.

**Comment by DaTebe** [comment]
Missing UI is not a big problem right now. If we can, let's just finish this backend scoped issue and then create a new issue for the frontend. :+1:
