### ISSUE TITLE
Add VMWare VMs as Resource

### ISSUE THREAD

**Issue by DaTebe** [FraunhoferISST/diva#353]
DIVA needs to inventory VMWare VMs.

## Schema
```json
{
  "resourceType": "vmware:vm",
  "title": "vm",
  "vmwareUuid": "56 4d d1 4a 8e 46 d6 79-87 7c dc 0d d7 4f ef e9",
  "vmwareProcessors": 4,
  "vmwareMemory": 16384,
  "vmwareHardDisk": 80,
  "vmwareGuestOs": "Ubuntu 22.04 64-bit"
}
```

## TODOs

- [x] add Schema files
- [x] add resourceType
- [x] add new field in web-client
- [x] get VMWare logo
- [ ] fix number fields in web client

**Comment by DaTebe** [comment]
![image](https://user-images.githubusercontent.com/12967305/211309868-2a89f3e7-3d33-4d2e-bf10-c054e0b58835.png)

**Comment by DaTebe** [comment]
![image](https://user-images.githubusercontent.com/12967305/211339756-2181a67a-fdd6-480e-a8ea-39223bde5aaa.png)

**Comment by DaTebe** [comment]
![image](https://user-images.githubusercontent.com/12967305/211339830-1630a0c8-2f9a-45a4-9f87-049ef034799b.png)
